#Monitorowanie wykonywanych polecen
-a always,exit -F arch=b64 -S execve -k command_execution
-a always,exit -F arch=b32 -S execve -k command_execution

#Monitorowanie zmian userow i hasel
-w /etc/passwd -p wa -k user_modification
-w /etc/shadow -p wa -k user_modification
-w /etc/group -p wa -k group_modification

#Monitorowanie sudo
-w /etc/sudoers -p wa -k sudoers_change
-w /usr/bin/sudo -p x -k sudo_usage

#Monitorowanie SSH
-w /etc/ssh/sshd_config -p wa -k ssh_config

#Monitorowanie login logout
-w /var/log/wtmp -p wa -k login_logout
-w /var/log/btmp -p wa -k failed_login
